name: Authenticate Gcloud Tools
description: Authenticates Gcloud tooling for use in the rest of the workflow
inputs:
  service_account:
    description: Service Account email to authenticate with
    required: true
  workload_identity_provider:
    description: ID of the workload identity provider
    required: true
  gcloud_project_id:
    description: ID of google cloud project
    required: true
  docker_host:
    description: Docker registry host to authorize with gcloud credentials
    required: false
    default: us-central1-docker.pkg.dev
runs:
  using: composite
  steps:
    - name: Setup gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ inputs.gcloud_project_id }}

    - name: Authenticate with Google Cloud
      id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - id: gcloud
      shell: bash
      name: Login gcloud tooling
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

    - name: Configure Docker credentials
      shell: bash
      run: |-
        gcloud --quiet auth configure-docker ${{ inputs.docker_host }}