name: Build and Push Docker Image
description: Builds a docker image and pushes to Google Cloud Artifact Registry
inputs:
  tags:
    description: Same as the `tags` input on the [Docker Metadata](https://github.com/docker/metadata-action#tags-input) action.
    required: false
    default: |
      type=ref,event=branch
      type=ref,event=tag
      type=sha,format=long
  registry:
    description: Registry for image
    required: true
  image_name:
    description: Name for image
    required: true
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: ${{ inputs.tags }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          GIT_SHA=${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha, mode=max
