name: QA Deployment

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        description: Name of the app that is being updated.
        required: true
      image_alias:
        type: string
        description: Image alias used in this apps Kustomize config
        required: true
      image_tag:
        type: string
        description: Image tag that should be deployed to qa.
        required: true
      service_account:
        type: string
        description: Service Account email to authenticate with
        required: true
      workload_identity_provider:
        type: string
        description: ID of the workload identity provider
        required: true
      gcloud_project_id:
        type: string
        description: ID of google cloud project
        required: true
      registry:
        type: string
        description: Registry for image
        required: true
      image_name:
        type: string
        description: Name for image
        required: true
    secrets:
      infra_repo_key:
        required: true

env:
  APP_NAME: ${{ inputs.app_name }}
  IMAGE_ALIAS: ${{ inputs.image_alias }}
  IMAGE_REPO: ${{ inputs.registry }}/${{ inputs.image_name }}
  IMAGE_TAG: ${{ inputs.image_tag }}

jobs:
  qa-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout infrastructure repository
        uses: actions/checkout@v2
        with:
          repository: gatedinc/infrastructure
          ssh-key: ${{ secrets.infra_repo_key }}
          path: infrastructure

      - name: Authenticate Google Cloud Tools
        uses: ./.github/actions/gcloud-auth
        with:
          service_account: ${{ inputs.service_account }}
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          gcloud_project_id: ${{ inputs.gcloud_project_id }}

      - name: Build & Push Docker Image
        uses: ./.github/actions/docker-build
        with:
          registry: ${{ inputs.registry }}
          image_name: ${{ inputs.image_name }}
          tags: |
            type=ref,event=pr
            type=raw,value=sha-${{ github.event.pull_request.head.sha }}

      - name: Select QA Environment
        id: select-qa-env
        uses: moonswitch/select-qa-env@v0.2.0
        with:
          table: qa-envs

      - name: Create QA deployment config file
        env:
          QA_LANE: ${{ steps.select-qa-env.outputs.env_name }}
          QA_FILE: ${{ steps.select-qa-env.outputs.env_name }}.json
          PR_NUMBER: ${{ github.event.number }}
          PR_SHA: ${{ github.sha }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
          PR_REPO: ${{ github.repository }}
          URL: ${{ steps.select-qa-env.outputs.url }}
        run: |-
          cd ${GITHUB_WORKSPACE}/infrastructure/qa-envs
          ./qa_apps.sh add
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . && git diff --cached --quiet || \
            git commit -m "[ci] Deploy PR-${{ github.event.number }} from ${{ github.repository }}" && \
            git push

      - name: Create QA Deployment
        uses: altinukshini/deployment-action@v1.2.6
        id: deployment
        with:
          pr: true
          pr_id: ${{ github.event.number }}
          transient_environment: true
          token: "${{ github.token }}"
          target_url: https://${{ steps.select-qa-env.outputs.url }}
          environment: ${{ steps.select-qa-env.outputs.env_name }}
          initial_status: success
          ref: ${{ github.event.pull_request.head.ref }}